### ISSUE TITLE
Problem with UV unwrap scale?

### ISSUE THREAD

**Issue by nbgo** [uhlik/render_maxwell#11]
Please look at this screenshot: https://s3.amazonaws.com/donnicky_screenshots/2016-05-28_22-11-41_3fc45883-3f85-488e-b2a6-816191ceef84.png

1m cube unwrapped using "Cube Projection" and it looks correct in UV editing as far as UV grid has 2 blender units size by default. But when exported to MXS I see that textures look twice bigger on cube then they should be: https://s3.amazonaws.com/donnicky_screenshots/2016-05-28_22-20-07_8b1c6606-d3e1-429c-93ff-e9f4a82be00f.png

**Comment by uhlik** [comment]
well, i think your understanding of uv mapping is incorrect a bit. there is no such think as absolute units. uv coordinates are always floating point numbers between zero and one. what you made in blender is following: cube face is scaled down to 1/4 area (1/2 edge size) and therefore you see just 4 squares instead of 16 because your face is covering 1/4 of uv area. scale the faces to fit whole area and you will get what you expect.. hope my explanation is not too confusing.

**Comment by nbgo** [comment]
I see. Thank you for explanation.
